title: "Karan Dave | SEO & Market Research Portfolio"
name: "Karan Dave"
description: "SEO Intern at Shaligram Infotech | BBA Student"
read_more: false
url: "https://karandave211.github.io"
repository: "karandave211/karandave211.github.io"
permalink: /:categories/:title/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-39Y9E5YXQ9"
    anonymize_ip: false

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
      sidebar:
        nav: "docs"

author:
  name: "Karan Dave"
  bio: "SEO Intern at Shaligram Infotech | BBA Student | Market Research Enthusiast"
  location: "Ahmedabad"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/karan-dave-984a883a8"

main:
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Resume"
    url: "/resume/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
