# Author Profile
author:
  name: "Karan Dave"
  bio: "SEO Intern | BBA Student"
  location: "Ahmedabad, India"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/karan-dave-984a883a8"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-39Y9E5YXQ9"
    anonymize_ip: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
