# Site Settings
title: "Karan Dave"
description: "BBA Student & Marketing Intern at Shaligram Infotech"
url: "https://karandave211.github.io"
baseurl: ""

# Theme Setup
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # This is a clean, white/blue professional skin

# SEO & Social
locale: "en-IN"
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/karan-dave-984a883a8/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      # Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed